GET http://localhost:8090/api/UserController

###
POST http://localhost:8090/api/UserController
Content-Type: application/json

{
    "Nome":"Mateus",
    "CPF": "48752698852",
    "Email": "j.felipe99@gmail.com",
    "Telefone": "977790862",
    "Sexo": "Masculino",
    "DataNascimento": "2009-02-15T00:00:00Z"
}